name: WCA German State Ranks Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: '00 18 *  *  *'
  workflow_dispatch:

jobs:
  get-ranks-write-to-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ⬇️
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install python packages 📦
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install -r requirements.txt

      - name: Execute python scripts ▶️
        run: |
          cd python
          python writer.py --automate True --test_statecup True

      # https://stackoverflow.com/a/74325815/22745629
      # Don't fail later when nothing to commit
      - name: Check changes via git ↔️
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      # Only run if there is something to commit
      - name: Commit changes ➕
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          pwd
          git commit -m "[auto] new WCA German State Ranks" -a

      # Only run if there is something to push
      - name: Push changes 🆙
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
